### ISSUE TITLE
Something went wrong while trying to get stauts of device 

### ISSUE THREAD

**Issue by arturlukosek** [Droccal/homebridge-lay-z-spa#5]
Today I have noticed that homekit didn't refresh the state of the spa. I found out Layz spa app require update to work. Looks like some changes ware done and now homebridge throw error in the console.

**Comment by arturlukosek** [comment]
Updated log. It seems I can control the spa but there is an error to fetch data and status is not updated in homekit. Log below: 

Something went wrong while trying to get stauts of device TypeError: Cannot read properties of undefined (reading 'power')
    at HotTubAccessory.getCurrentStatus (/usr/local/lib/node_modules/homebridge-lay-z-spa/src/HotTubAccessory.ts:145:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lay-z-spa/src/HotTubAccessory.ts:117:9)

**Comment by Holydevil66** [comment]
Same here since yesterday; seems like they changed something in the API as they also released a new version of the lay-z-spa app some days ago…

**Comment by Droccal** [comment]
Hey guys, thanks for the report, I will try to fix that asap, currently I don’t have the whirlpool installed and therefore can’t really test it, but I plan to do it the following week!

**Comment by Droccal** [comment]
Good news guys, I managed to upgrade and use the new api - I tested with my whirlpool and it was working well! hope you can confirm that this is working now - if not please report back with some error messages please.

**Comment by arturlukosek** [comment]
Hi @Droccal thank you for the effort but unfortunately after latest plugin update I have no control of the spa anymore. Previously I could send some requests and issues was with the getting state. At the moment I dont get the homebridge error like above but spa don't react on any comments from homekit. I just did a quick test. Will check tomorrow and post more feedback.

**Comment by Oddy9923857** [comment]
19/06/2023, 00:50:57Lay Z Spa Bridge starting
19/06/2023, 00:51:01Lay Z Spa BridgeLoaded plugin 'homebridge-lay-z-spa'
19/06/2023, 00:51:01Lay Z Spa BridgeLoading 1 platforms...
19/06/2023, 00:51:01Lay Z Spa BridgeWhirlpoolLoading accessory from cache: Whirlpool
19/06/2023, 00:51:01Lay Z Spa BridgeBridge is running on port 51876.
19/06/2023, 00:51:01Lay Z Spa BridgeWhirlpoolERRORCould not retrieve api key. Status 400

**Comment by Oddy9923857** [comment]
Also using the GitHub blob you used to query the API - I get an error page when posting to https://mobileapi.lay-z-spa.co.uk/v1/auth/login? using my email and password. My Lay-Z-Spa app was updated recently and is working. They have changed the API for sure and perhaps implemented some more advanced device detection maybe?

**Comment by Droccal** [comment]
yes definitly they changed something in the api, there is now some sort of salting and hashing of the request parameters. I don't think it will be easy to find out how this is done - this is why I changed to the bestway app. I could integrate my whirlpool with their app and use it from there and now also via this updated plugin.
